### ISSUE TITLE
t/01.organisation.t started to fail

### ISSUE THREAD

**Issue by eserte** [hatorikibble/webservice-lobid-organisations#1]
See subject. There are no more pass reports since some days. See also:
* http://matrix.cpantesters.org/?dist=WebService-Lobid-Organisation%200.0031;reports=1#sl=7,1 (for an overview)
* http://www.cpantesters.org/cpan/report/05cac0c4-0cd6-11e9-9312-ee9892007808 (a sample fail report)

**Comment by hatorikibble** [comment]
Thanks! I will look into it in the next few days.

Best regards,

 Peter

Am 7. Januar 2019 20:42:51 MEZ schrieb "Slaven Rezić" <notifications@github.com>:
>See subject. There are no more pass reports since some days. See also:
>*
>http://matrix.cpantesters.org/?dist=WebService-Lobid-Organisation%200.0031;reports=1#sl=7,1
>(for an overview)
>*
>http://www.cpantesters.org/cpan/report/05cac0c4-0cd6-11e9-9312-ee9892007808
>(a sample fail report)
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/hatorikibble/webservice-lobid-organisations/issues/1

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by hatorikibble** [comment]
Thanks again, i trialed and submitted a new version and so far the test reports look good.
